#!/usr/bin/env bash
# Installing Nginx on the server

sudo apt-get update
sudo apt-get install -y nginx
sudo bash -c 'echo "Holberton School" > /var/www/html/index.nginx-debian.html'
service nginx restart
