#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx
sudo bash -c 'echo "Holberton School" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/server_name _/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
sudo service nginx restart
