#!/usr/bin/env bash
#install load balacer
apt-get -y update
apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/original.cfg
echo "
frontend front
    bind *:80
    mode http
    default_backend backend-web
backend backend-web
    balance roundrobin
    server 1794-web-01 	35.231.249.46:80 check
    server 1794-web-02 34.75.248.93:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
