#!/usr/bin/env bash
# Installs and configure HAproxy on your lb-01 server

apt-get -y update
apt-get install -y haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
echo "
frontend front
    bind *:80
    mode http
    default_backend backend-web
backend backend-web
    balance roundrobin
    server 1794-web-01 35.231.249.46 check
    server 1794-web-02 34.75.248.93 check" >> /etc/haproxy/haproxy.cfg

service haproxy start
