#!/usr/bin/env bash
# Write a Bash script that:
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

holberton=/var/run/holbertonscript.pid
echo $$ > $holberton

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm $tmp_file; exit' SIGTERM
trap 'rm $tmp_file; exit' SIGQUIT

while "true"
do
    echo "To infinity and beyond"
    sleep 2
done
