#!/usr/bin/env bash
# Holberton School 10 times, but for the 9th iteration, displays Holberton School and Hi

counter=1
name="Holberton School"
hi="Hi"
while [ $counter -le 10 ]
do
    echo $name
    if [ $counter -eq 9 ]
    then
        echo $hi
    fi
    ((counter++))
done
