#!/usr/bin/env bash
# Bash script that loops from 1 to 10

counter=1
name="Holberton School"
bad="bad luck"
good="good luck"

while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo "$bad"
    elif [ $counter -eq 8 ]
    then
        echo "$good"
    else
        echo "$name"
    fi
    ((counter++))
done
